version: '3.7'
services:
  arangodb_db_container:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: root
    ports:
      - 8529:8529
    volumes:
      - data_container:/var/lib/arangodb3
      - apps_data_container:/var/lib/arangodb3-apps

volumes:
  data_container:
  apps_data_container: