version: '3.3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'anydone'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - data:/var/lib/mysql
  pma:
    image: phpmyadmin
    depends_on:
      - mysql
    restart: always
    environment:
      - PMA_HOST=mysql
    ports:
      - "8081:80"
# Names our volume
volumes:
  data: