version: '3'
services:
  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
      - ./delete.xml:/home/solr/delete.xml
      - ./conf/:/home/solr/conf/
      - ./create_collection.sh:/home/solr/create_collection.sh
      # - ./security.json:/var/solr/data/security.json
volumes:
  data: