version: '3'
services:
  redis:
    image: redis:latest
    command: redis-server --requirepass password
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - data:/data
      - ./redis.conf:/conf/redis.conf
volumes:
  data: